all:
  vars:
    control_plane_endpoint: 192.168.1.211
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.200, mac: 'ec:b1:d7:6b:29:cf', disk: nvme0n1, network_interface: eno1}
        metal1: {ansible_host: 192.168.1.201, mac: 'ec:b1:d7:6b:2e:ee', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 192.168.1.202, mac: 'ec:b1:d7:6b:40:cd', disk: nvme0n1, network_interface: eno1}

