home-assistant:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Home-Assistant
        hajimari.io/icon: google-drive
        nginx.org/websocket-services: home-assistant
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.danger250.com"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      hosts:
        - host: &host home-assistant.danger250.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: home-assistant-tls-certificate
          hosts:
            - *host
  lifecycle:
    preStop:
      exec:
        command:
          - "/bin/sh"
          - "-c"
          - cp -f configuration.yaml_new configuration.yaml;
            wget -O - https://get.hacs.xyz | bash -;
            if [ ! -d ./media ]; then
            mkdir media;
            fi;
            if [ ! -d ./www ]; then
            mkdir www;
            fi;
  persistence:
    config:
      enabled: true
      size: 2Gi
    configfile:
      enabled: true
      name: home-assistant-configfile
      items:
        - key: configuration
          path: configuration.yaml_new
      type: configMap
      mountPath:  /config/configuration.yaml_new
      subPath: configuration.yaml_new
  configmap:
    configfile:
      enabled: true
      data:
        configuration: |
          # Loads default set of integrations. Do not remove.
          default_config:

          # Load frontend themes from the themes folder
          frontend:
            themes: !include_dir_merge_named themes

          sensor:
            - platform: swiss_public_transport
              from: 8589846
              to: 8508450
            - platform: swiss_public_transport_mod
              name: Weinbergli
              limit: 4
              stationboard:
                - Luzern, Weinbergli
  addons:
    codeserver:
      enabled: true
      args:
        - --auth
        - none
        - --user-data-dir
        - /data/config/.vscode
      volumeMounts:
        - name: config
          mountPath: /data/config